### ISSUE TITLE
npm run buildのエラー

### ISSUE THREAD

**Issue by tatsuyard** [tatsuyard/scotch-whisky#20]
```
> Build error occurred                                                                              │±
TypeError: app_default.a.firestore is not a function                                                │
    at Module.fV0D (/usr/src/app/.next/server/pages/brand.js:2103:35)                               │
    at __webpack_require__ (/usr/src/app/.next/server/pages/brand.js:23:31)                         │
    at Object.4 (/usr/src/app/.next/server/pages/brand.js:454:18)                                   │
    at __webpack_require__ (/usr/src/app/.next/server/pages/brand.js:23:31)                         │
    at /usr/src/app/.next/server/pages/brand.js:91:18                                               │
    at Object.<anonymous> (/usr/src/app/.next/server/pages/brand.js:94:10)                          │
    at Module._compile (internal/modules/cjs/loader.js:1063:30)                                     │
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)                       │
    at Module.load (internal/modules/cjs/loader.js:928:32)                                          │
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {                              │
  type: 'TypeError'                                                                                 │
}
```

**Comment by tatsuyard** [comment]
一時的にDockerfileからbuildをコメントアウト

**Comment by tatsuyard** [comment]
ref
https://github.com/firebase/firebase-js-sdk/issues/752#issuecomment-389605982

**Comment by tatsuyard** [comment]
initFirebaseが必要だったわけだがいちいち初期化するのも問題なので別途issueを切る
